version: "3.2"
services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:latest"
    ports:
      - "27017:27017"
  redis:
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    container_name: "postgres"
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: user
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "5434:5432"