// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller.hello.dependency.go

// Package hello is a generated GoMock package.
package hello

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHelloRepositoryInterface is a mock of HelloRepositoryInterface interface.
type MockHelloRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHelloRepositoryInterfaceMockRecorder
}

// MockHelloRepositoryInterfaceMockRecorder is the mock recorder for MockHelloRepositoryInterface.
type MockHelloRepositoryInterfaceMockRecorder struct {
	mock *MockHelloRepositoryInterface
}

// NewMockHelloRepositoryInterface creates a new mock instance.
func NewMockHelloRepositoryInterface(ctrl *gomock.Controller) *MockHelloRepositoryInterface {
	mock := &MockHelloRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockHelloRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloRepositoryInterface) EXPECT() *MockHelloRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetHelloFromMongo mocks base method.
func (m *MockHelloRepositoryInterface) GetHelloFromMongo() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetHelloFromMongo")
}

// GetHelloFromMongo indicates an expected call of GetHelloFromMongo.
func (mr *MockHelloRepositoryInterfaceMockRecorder) GetHelloFromMongo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelloFromMongo", reflect.TypeOf((*MockHelloRepositoryInterface)(nil).GetHelloFromMongo))
}

// GetHelloMessage mocks base method.
func (m *MockHelloRepositoryInterface) GetHelloMessage() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelloMessage")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHelloMessage indicates an expected call of GetHelloMessage.
func (mr *MockHelloRepositoryInterfaceMockRecorder) GetHelloMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelloMessage", reflect.TypeOf((*MockHelloRepositoryInterface)(nil).GetHelloMessage))
}
